import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen antialiased`}
      >
        <header className="flex justify-between items-center w-full h-12 px-4 py-2 bg-teal-300 dark:bg-teal-700 text-black dark:text-white">
          <Link
            href="/"
            target=""
            rel="noopener noreferrer"
          >
            <Image
              className="dark:invert"
              src="/next.svg"
              alt="Aqualab logo"
              width={100}
              height={20}
              priority
            />
          </Link>
          <div>
            <nav className="flex flex-row gap-4">
              <button>about us</button>
              <button>monitor</button>
            </nav>
          </div>
        </header>
        {children}
        <footer className="w-full h-12 px-4 py-2 bg-teal-100 dark:bg-teal-900 text-black dark:text-white">
          Aqualab
        </footer>
      </body>
    </html>
  );
}
